import = [
    "~/.dotfiles/alacritty/themes/kanagawa_wave.toml"
]

[font]
size = 8.5

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[window]
opacity = 0.7
